version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "02:30"
    timezone: America/Los_Angeles
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: broccoli-asset-rev
  - dependency-name: concurrently
  - dependency-name: "@ember/optional-features"
  - dependency-name: "@ember/test-helpers"
  - dependency-name: "@embroider/test-setup"
  - dependency-name: ember-auto-import
  - dependency-name: ember-cli
  - dependency-name: ember-cli-babel
  - dependency-name: ember-cli-dependency-checker
  - dependency-name: ember-cli-eslint
  - dependency-name: ember-cli-htmlbars
  - dependency-name: ember-cli-htmlbars-inline-precompile
  - dependency-name: ember-cli-inject-live-reload
  - dependency-name: ember-cli-sri
  - dependency-name: ember-cli-template-lint
  - dependency-name: ember-cli-uglify
  - dependency-name: ember-disable-prototype-extensions
  - dependency-name: ember-export-application-global
  - dependency-name: ember-load-initializers
  - dependency-name: ember-qunit
  - dependency-name: ember-resolver
  - dependency-name: ember-source
  - dependency-name: ember-source-channel-url
  - dependency-name: ember-try
  - dependency-name: eslint
  - dependency-name: eslint-plugin-ember
  - dependency-name: eslint-plugin-node
  - dependency-name: loader.js
  - dependency-name: qunit-dom
  - dependency-name: webpack
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: daily
