version: 1

update_configs:
  - package_manager: javascript
    directory: "/"
    update_schedule: daily
    ignored_updates:
    # ignore everything ember-cli provides in the blueprint
    - match:
        dependency_name: "ember-cli-babel"
    - match:
        dependency_name: "@ember/jquery"
    - match:
        dependency_name: "@ember/optional-features"
    - match:
        dependency_name: "broccoli-asset-rev"
    - match:
        dependency_name: "ember-cli"
    - match:
        dependency_name: "ember-cli-dependency-checker"
    - match:
        dependency_name: "ember-cli-eslint"
    - match:
        dependency_name: "ember-cli-htmlbars"
    - match:
        dependency_name: "ember-cli-htmlbars-inline-precompile"
    - match:
        dependency_name: "ember-cli-inject-live-reload"
    - match:
        dependency_name: "ember-cli-sri"
    - match:
        dependency_name: "ember-cli-template-lint"
    - match:
        dependency_name: "ember-cli-uglify"
    - match:
        dependency_name: "ember-disable-prototype-extensions"
    - match:
        dependency_name: "ember-export-application-global"
    - match:
        dependency_name: "ember-load-initializers"
    - match:
        dependency_name: "ember-maybe-import-regenerator"
    - match:
        dependency_name: "ember-qunit"
    - match:
        dependency_name: "ember-resolver"
    - match:
        dependency_name: "ember-source"
    - match:
        dependency_name: "ember-source-channel-url"
    - match:
        dependency_name: "ember-try"
    - match:
        dependency_name: "eslint-plugin-ember"
    - match:
        dependency_name: "eslint-plugin-node"
    - match:
        dependency_name: "loader.js"
    - match:
        dependency_name: "qunit-dom"
    automerged_updates:
    - match:
        dependency_name: "ember-auto-import"
    - match:
        dependency_name: "ember-cli-mirage"
    - match:
        dependency_name: "ember-cli-moment-shim"
    - match:
        dependency_name: "ember-cli-page-object"
    - match:
        dependency_name: "ember-moment"
    - match:
        dependency_name: "ember-test-selectors"
    - match:
        update_type: "semver:minor"
        dependency_name: "@fortawesome/pro-light-svg-icons"
    - match:
        update_type: "semver:minor"
        dependency_name: "@fortawesome/pro-regular-svg-icons"
    - match:
        update_type: "semver:minor"
        dependency_name: "@fortawesome/pro-solid-svg-icons"
    - match:
        update_type: "semver:minor"
        dependency_name: "@fortawesome/free-brands-svg-icons"
    - match:
        update_type: "semver:minor"
        dependency_name: "@fortawesome/free-regular-svg-icons"
    - match:
        update_type: "semver:minor"
        dependency_name: "@fortawesome/free-solid-svg-icons"
    - match:
        dependency_name: "@ilios/ember-template-lint-plugin"
    - match:
        dependency_name: "@ilios/eslint-config-ember-addon"
    - match:
        dependency_name: "ember-cli-deprecation-workflow"
    - match:
        dependency_name: "ember-qunit-nice-errors"
    - match:
        dependency_name: "ember-template-lint"
    - match:
        dependency_name: "eslint"
    - match:
        dependency_name: "pre-commit"
    - match:
        dependency_name: "stylelint"
    - match:
        dependency_name: "stylelint-config-recommended-scss"
    - match:
        dependency_name: "stylelint-scss"
