name: Percy Visual Tests

on:
  schedule:
    - cron: "15 23 * * 2,4" # T,Th in the afternoon (UTC)
  workflow_dispatch:

concurrency:
  group: percy-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

env:
  SW_DISABLED: true
  COVERAGE: false
  PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
  SLACK_WEBHOOK_URL: ${{ secrets.SLACK_ILIOS_DEPLOYMENT_WEBHOOK_URL }}

jobs:
  percy:
    name: Test and Capture Screenshots
    runs-on: ubuntu-latest
    timeout-minutes: 20
    strategy:
      fail-fast: false
      matrix:
        workspace:
          - frontend
          - test-app
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm
      - run: pnpm install
      - name: Run Percy Tests
        run: pnpm --filter ${{matrix.workspace}} exec percy exec -- ember test
      - uses: act10ns/slack@v2
        if: failure()
        with:
          status: ${{ job.status }}
          message: Percy Run Failed {{ env.GITHUB_SERVER_URL }}/{{ env.GITHUB_REPOSITORY }}/actions/runs/{{ env.GITHUB_RUN_ID }}
